spring.application.name=spring-auth-system
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_system_db
spring.datasource.username=abdulkhadir
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
